# Generated by Django 3.1 on 2020-10-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosCorpciti', '0005_auto_20201002_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='congreso_seminario',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='congreso_seminario',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
